"""Edit Category

Revision ID: f103673e8ebe
Revises: de8b0b72592f
Create Date: 2025-04-19 17:21:49.842352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f103673e8ebe"
down_revision: Union[str, None] = "de8b0b72592f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_categories_name", table_name="categories")
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.create_index("ix_categories_name", "categories", ["name"], unique=False)
    # ### end Alembic commands ###
